apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-service.fullname" . }}-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.datasource.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.datasource.password | quote }}