spring:
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/my-bank
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/my-bank
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybank:
  clients:
    accounts-service:
      service-id: accounts-service
    notifications-service:
      service-id: notifications-service
    transfer-service:
      service-id: transfer-service
    cash-service:
      service-id: cash-service