spring:
  datasource:
    url: jdbc:postgresql://localhost:${CASH_DB_PORT:5435}/${CASH_DB_NAME:cash}
    username: ${CASH_DB_USER:admin}
    password: ${CASH_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          cash-service:
            provider: keycloak
            client-id: cash-service
            client-secret: ${KEYCLOAK_CASH_SERVICE_SECRET:kUU6hqgpFDhYF1lmlERvQowrDerIbLa5}
            authorization-grant-type: client_credentials