fullnameOverride: "accounts-service"

image:
  repository: accounts-service
  tag: "0.0.1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8080

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 10

liquibase:
  enabled: true

datasource:
  url: "jdbc:postgresql://accounts-db:5432/accounts"
  username: admin
  password: password