spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cash-ui
              uri: lb://cash-service
              predicates:
                - Path=/customers/me/deposits,/customers/me/withdrawals

            - id: transfer-ui
              uri: lb://transfer-service
              predicates:
                - Path=/customers/me/transfers

            - id: accounts-ui
              uri: lb://accounts-service
              predicates:
                - Path=/customers/me,/customers/me/profile,/customers/me/recipient-candidates,/wallets/me
server:
  port: ${SERVER_PORT:8080}
