services:
  keycloak-db:
    image: postgres:17.6-alpine3.22
    container_name: bank-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: bank-keycloak
    command: start-dev --import-realm
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DB: postgres
      KEYCLOAK_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KEYCLOAK_DB_USERNAME: keycloak
      KEYCLOAK_DB_PASSWORD: keycloak
    ports:
      - "18080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  keycloak-db-data:
