apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}-config
data:
  LIQUIBASE_ENABLED: {{ default true .Values.liquibase.enabled | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.datasource.url | quote }}
  ACCOUNTS_SERVICE_URL: {{ .Values.clients.accountsServiceUrl | quote }}
  NOTIFICATIONS_SERVICE_URL: {{ .Values.clients.notificationsServiceUrl | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuerUri | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC_TRANSFER_CREATED: {{ .Values.kafka.topics.transferCreated | quote }}
