spring:
  datasource:
    url: jdbc:postgresql://localhost:${CASH_DB_PORT:5435}/${CASH_DB_NAME:cash}
    username: ${CASH_DB_USER:admin}
    password: ${CASH_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver