server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: cash-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/my-bank
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/my-bank
        registration:
          cash-service:
            provider: keycloak
            client-id: cash-service
            client-secret: ${KEYCLOAK_CASH_SERVICE_SECRET:kUU6hqgpFDhYF1lmlERvQowrDerIbLa5}
            authorization-grant-type: client_credentials
  datasource:
    url: jdbc:postgresql://localhost:${CASH_DB_PORT:5435}/${CASH_DB_NAME:cash}
    username: ${CASH_DB_USER:admin}
    password: ${CASH_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
mybank:
  clients:
    accounts-service:
      service-id: accounts-service
    notifications-service:
      service-id: notifications-service
