spring:
  application:
    name: cash-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          cash-service:
            provider: keycloak
            client-id: cash-service
            client-secret: ${KEYCLOAK_CASH_SERVICE_SECRET}
            authorization-grant-type: client_credentials
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
mybank:
  clients:
    accounts-service:
      base-url: ${ACCOUNTS_SERVICE_URL}
  kafka:
    topics:
      walletOperationCompleted: ${KAFKA_TOPIC_WALLET_OPERATION_COMPLETED}
