apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-service.fullname" . }}-config
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}

  KAFKA_CONSUMER_GROUP_ID: {{ .Values.kafka.consumer.groupId | quote }}
  KAFKA_AUTO_OFFSET_RESET: {{ .Values.kafka.consumer.autoOffsetReset | quote }}

  KAFKA_TOPIC_WALLET_OPERATION_COMPLETED: {{ .Values.kafka.topics.walletOperationCompleted | quote }}
  KAFKA_TOPIC_TRANSFER_CREATED: {{ .Values.kafka.topics.transferCreated | quote }}
  KAFKA_TOPIC_WALLET_OPERATION_COMPLETED_DLQ: {{ .Values.kafka.topics.walletOperationCompletedDlq | quote }}
  KAFKA_TOPIC_TRANSFER_CREATED_DLQ: {{ .Values.kafka.topics.transferCreatedDlq | quote }}

  KAFKA_ERROR_MAX_RETRIES: {{ .Values.kafka.errorHandling.maxRetries | quote }}
  KAFKA_ERROR_INITIAL_INTERVAL_MS: {{ .Values.kafka.errorHandling.initialIntervalMs | quote }}
  KAFKA_ERROR_MULTIPLIER: {{ .Values.kafka.errorHandling.multiplier | quote }}
  KAFKA_ERROR_MAX_INTERVAL_MS: {{ .Values.kafka.errorHandling.maxIntervalMs | quote }}
  KAFKA_ERROR_DLQ_SUFFIX: {{ .Values.kafka.errorHandling.dlqSuffix | quote }}