spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/my-bank
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/my-bank
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: ${KEYCLOAK_TRANSFER_SERVICE_SECRET:c1GviQ8G2PRXYZ1FbEq29XdZGywY6dQ1}
            authorization-grant-type: client_credentials
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  threads:
    virtual:
      enabled: true
server:
  port: ${SERVER_PORT:8083}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybank:
  clients:
    accounts-service:
      service-id: accounts-service
    notifications-service:
      service-id: notifications-service
