server:
  port: ${SERVER_PORT:8083}
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/my-bank}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/my-bank}
        registration:
          transfer-service:
            client-id: transfer-service
            client-secret: ${KEYCLOAK_TRANSFER_SERVICE_SECRET:dev-secret}
            authorization-grant-type: client_credentials
  datasource:
    url: ${TRANSFER_DB_URL:jdbc:postgresql://localhost:${TRANSFER_DB_PORT:5436}/${TRANSFER_DB_NAME:transfer}}
    username: ${TRANSFER_DB_USER:admin}
    password: ${TRANSFER_DB_PASSWORD:password}
  liquibase:
    enabled: true
mybank:
  clients:
    accounts-service:
      base-url: ${ACCOUNTS_SERVICE_URL:http://localhost:8081}
    notifications-service:
      base-url: ${NOTIFICATIONS_SERVICE_URL:http://localhost:8085}