spring:
  application:
    name: transfer-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  threads:
    virtual:
      enabled: true
server:
  port: ${SERVER_PORT:8083}
clients:
  accounts:
    base-url: http://accounts-service
  notifications:
    base-url: http://notifications-service
