spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: ${KEYCLOAK_TRANSFER_SERVICE_SECRET}
            authorization-grant-type: client_credentials
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
mybank:
  clients:
    accounts-service:
      base-url: ${ACCOUNTS_SERVICE_URL}
    notifications-service:
      base-url: ${NOTIFICATIONS_SERVICE_URL}
