spring:
  datasource:
    url: jdbc:postgresql://localhost:${TRANSFER_DB_PORT:5436}/${TRANSFER_DB_NAME:transfer}
    username: ${TRANSFER_DB_USER:admin}
    password: ${TRANSFER_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver