apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
data:
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuerUri | quote }}
  CASH_SERVICE_URL: {{ .Values.routes.cashServiceUrl | quote }}
  TRANSFER_SERVICE_URL: {{ .Values.routes.transferServiceUrl | quote }}
  ACCOUNTS_SERVICE_URL: {{ .Values.routes.accountsServiceUrl | quote }}
