apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-service.fullname" . }}-config
data:
  LIQUIBASE_ENABLED: {{ default true .Values.liquibase.enabled | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.datasource.url | quote }}
  ACCOUNTS_SERVICE_URL: {{ .Values.clients.accountsServiceUrl | quote }}
  NOTIFICATIONS_SERVICE_URL: {{ .Values.clients.notificationsServiceUrl | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuerUri | quote }}

