apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-service.fullname" . }}-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ default "admin" .Values.datasource.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ default "password" .Values.datasource.password | quote }}
  KEYCLOAK_CASH_SERVICE_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
