fullnameOverride: "api-gateway"

image:
  repository: api-gateway
  tag: "0.0.1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8080

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 10

routes:
  cashServiceUrl: "http://cash-service:8080"
  transferServiceUrl: "http://transfer-service:8080"
  accountsServiceUrl: "http://accounts-service:8080"

# comes from umbrella bank chart
global:
  keycloakIssuerUri: ""
