apiVersion: v1
kind: Service
metadata:
  name: {{ include "accounts-db.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "accounts-db.fullname" . }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: 5432
