spring:
  datasource:
    url: jdbc:postgresql://localhost:${ACCOUNTS_DB_PORT:5434}/${ACCOUNTS_DB_NAME:accounts}
    username: ${ACCOUNTS_DB_USER:admin}
    password: ${ACCOUNTS_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver