apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-controller.fullname" . }}-config
data:
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuerUri | quote }}
  API_GATEWAY_URL: {{ .Values.config.apiGatewayUrl | quote }}
