apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-controller.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "front-controller.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
