spring:
  application:
    name: front-controller
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        client:
          provider:
            keycloak:
              issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          keycloak:
            client-id: front-ui
            authorization-grant-type: authorization_code
            scope: openid,profile,email
mybank:
  clients:
    accounts-service:
      base-url: ${API_GATEWAY_URL}
    transfer-service:
      base-url: ${API_GATEWAY_URL}
    cash-service:
      base-url: ${API_GATEWAY_URL}