server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: front-controller
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/my-bank
      client:
        client:
          provider:
            keycloak:
              issuer-uri: http://localhost:18080/realms/my-bank
        registration:
          keycloak:
            client-id: front-ui
            authorization-grant-type: authorization_code
            scope: openid,profile,email
mybank:
  clients:
    accounts-service:
      service-id: api-gateway
    transfer-service:
      service-id: api-gateway
    cash-service:
      service-id: api-gateway