apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-service-config
  namespace: dev
data:
  KEYCLOAK_ISSUER_URI: "http://${HOST_IP}:18080/realms/my-bank"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://cash-db:5432/cash"
  LIQUIBASE_ENABLED: "true"
  ACCOUNTS_SERVICE_URL: "http://accounts-service:8080"
  NOTIFICATIONS_SERVICE_URL: "http://notifications-service:8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: cash-service-secret
  namespace: dev
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "password"
  KEYCLOAK_CASH_SERVICE_SECRET: 1vOiZvFTjska5Kht5DT3AFhieQxJaPAm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
    spec:
      containers:
        - name: app
          image: cash-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: cash-service-config
            - secretRef:
                name: cash-service-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: cash-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: cash-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
