apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-db.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
